"""empty message

Revision ID: 15406f38652e
Revises: e40cd041ce06
Create Date: 2022-05-19 16:34:25.584159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15406f38652e'
down_revision = 'e40cd041ce06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_company', sa.Boolean(), nullable=True))
    op.drop_column('user', 'investor_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('investor_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_company')
    # ### end Alembic commands ###
