"""empty message

Revision ID: 23fd3fb01830
Revises: 15406f38652e
Create Date: 2022-05-26 17:14:19.614326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fd3fb01830'
down_revision = '15406f38652e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acepted_conditions', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('inversor_type', sa.String(length=120), nullable=True))
    op.drop_column('user', 'is_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_company', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'inversor_type')
    op.drop_column('user', 'acepted_conditions')
    # ### end Alembic commands ###
