"""empty message

Revision ID: 46c39bf70e3c
Revises: 13dd3914e8d9
Create Date: 2022-05-17 19:15:00.603995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c39bf70e3c'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('country', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('investor_type', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'usertype', ['user_type'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'is_premium')
    op.drop_column('user', 'investor_type')
    op.drop_column('user', 'country')
    op.drop_table('usertype')
    # ### end Alembic commands ###
