"""empty message

Revision ID: e28ec5d0a896
Revises: c41ac3313386
Create Date: 2022-05-19 13:24:39.554042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28ec5d0a896'
down_revision = 'c41ac3313386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertype', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertype', sa.Column('user_type', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
