"""empty message

Revision ID: e40cd041ce06
Revises: b5a86e0ae975
Create Date: 2022-05-19 14:34:16.470005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40cd041ce06'
down_revision = 'b5a86e0ae975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_project_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'project_id')
    op.add_column('project', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'category_id')
    op.add_column('category', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_project_id_fkey', 'category', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
