"""empty message

Revision ID: e5c5c23596fc
Revises: a75da5983a67
Create Date: 2022-06-16 16:58:47.263297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c5c23596fc'
down_revision = 'a75da5983a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('mensajes', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.drop_constraint('mensajes_sender_user_fkey', 'mensajes', type_='foreignkey')
    op.create_foreign_key(None, 'mensajes', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'mensajes', 'user', ['sender_id'], ['id'])
    op.drop_column('mensajes', 'sender_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('sender_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.create_foreign_key('mensajes_sender_user_fkey', 'mensajes', 'user', ['sender_user'], ['id'])
    op.drop_column('mensajes', 'receiver_id')
    op.drop_column('mensajes', 'sender_id')
    # ### end Alembic commands ###
